{
    "Service": "/RisksMobile/Services/RiskManagementService.service",
    "DefiningRequests": [{
            "Name": "Mitigations",
            "Query": "Mitigations"
        },
        {
            "Name": "Risks",
            "Query": "Risks"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "$(L,Action_Init_Activity)",
    "ActionResult": {
        "_Name": "init"
    },
    "OnFailure": "/RisksMobile/Actions/RiskManagementService/Service/InitializeOfflineFailureMessage.action",
    "OnSuccess": "/RisksMobile/Actions/RiskManagementService/Service/InitializeOfflineSuccessMessage.action"
}