{
    "ActionResult": {
        "_Name": "UploadLog"
    },
    "ActivityIndicatorText": "$(L,Action_Log_Upload_Activity)",
    "OnFailure": "/RisksMobile/Actions/Logging/LogUploadFailure.action",
    "OnSuccess": "/RisksMobile/Actions/Logging/LogUploadSuccessful.action",
    "ShowActivityIndicator": false,
    "_Type": "Action.Type.Logger.Upload"
}